-- Run in a test SQL session. All fixtures, orders and notifications roll back.
begin;
create temp table offer_test_fixture as select gen_random_uuid() as seller_id, gen_random_uuid() as buyer_id, gen_random_uuid() as product_id;
grant select on offer_test_fixture to anon, authenticated;
insert into auth.users(id, email) select seller_id,'offer-test-seller-'||seller_id||'@example.invalid' from offer_test_fixture union all select buyer_id,'offer-test-buyer-'||buyer_id||'@example.invalid' from offer_test_fixture;
insert into public.users(id, full_name, phone_number, role) select seller_id,'Offer test seller','+220831000001','seller'::public.user_role from offer_test_fixture union all select buyer_id,'Offer test buyer','+220831000002','buyer'::public.user_role from offer_test_fixture;
insert into public.sellers(id,business_name,verification_status,delivery_regions) select seller_id,'Offer test shop','approved',array['Kanifing'] from offer_test_fixture;
insert into public.seller_delivery_areas(seller_id,region,area,delivery_fee) select seller_id,'Kanifing','Offer test area',50 from offer_test_fixture;
insert into public.products(id,seller_id,title,price,stock_quantity,location_city) select product_id,seller_id,'Offer test listing',1000.99,20,'Serekunda' from offer_test_fixture;
create function pg_temp.assert_true(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'TEST FAILED: %',label; end if; end$$;
create function pg_temp.expect_error(stmt text,needle text) returns void language plpgsql as $$begin execute stmt; raise exception 'TEST FAILED: statement unexpectedly succeeded'; exception when others then if position(needle in sqlerrm)=0 then raise; end if; end$$;
grant execute on function pg_temp.assert_true(boolean,text),pg_temp.expect_error(text,text) to anon, authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub',seller_id::text,true) from offer_test_fixture;
insert into public.product_offers(product_id,seller_id,kind,percent_off,expires_at) select product_id,seller_id,'discount',20,now()+interval '7 days' from offer_test_fixture;
select pg_temp.assert_true((select effective_price=800.79 from public.marketplace_priced_products where id=(select product_id from offer_test_fixture)),'seller creates 20% discount, cents round correctly');
reset role;
set local role anon;
select set_config('request.jwt.claim.sub','',true);
select pg_temp.assert_true((select count(*)=1 from public.product_offers where product_id=(select product_id from offer_test_fixture)),'guest sees live deal');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub',buyer_id::text,true) from offer_test_fixture;
update public.product_offers set percent_off=90 where product_id=(select product_id from offer_test_fixture);
select pg_temp.assert_true((select percent_off=20 from public.product_offers where product_id=(select product_id from offer_test_fixture)),'buyer cannot edit seller offer');
select pg_temp.expect_error(format('select public.create_marketplace_order_v3(%L,1,%L,%L,%L,%L,null,null,null,null,null,1)',product_id,'Kanifing','Offer test area','Test delivery address','+220831000002'),'Offer price changed') from offer_test_fixture;
create temp table test_orders as select public.create_marketplace_order_v3(product_id,2,'Kanifing','Offer test area','Test delivery address','+220831000002',null,null,null,null,null,800.79) as id from offer_test_fixture;
select pg_temp.assert_true((select price_at_purchase=800.79 and original_unit_price=1000.99 and offer_percent_off=20 and quantity=2 from public.order_items where order_id=(select id from test_orders)),'order persists discounted unit price and original price');
select pg_temp.assert_true((select delivery_fee=50 from public.orders where id=(select id from test_orders)),'delivery fee is not discounted');
select pg_temp.assert_true((select stock_quantity=18 from public.products where id=(select product_id from offer_test_fixture)),'stock reduced atomically');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub',seller_id::text,true) from offer_test_fixture;
update public.product_offers set kind='voucher',voucher_code='SAVE15',percent_off=15 where product_id=(select product_id from offer_test_fixture);
select pg_temp.expect_error(format('select public.create_marketplace_order_v3(%L,1,%L,%L,%L,%L,null,null,null,null,%L,850.84)',product_id,'Kanifing','Offer test area','Test delivery address','+220831000002','SAVE15'),'You cannot buy your own product') from offer_test_fixture;
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub',buyer_id::text,true) from offer_test_fixture;
select pg_temp.expect_error(format('select public.create_marketplace_order_v3(%L,1,%L,%L,%L,%L,null,null,null,null,%L,850.84)',product_id,'Kanifing','Offer test area','Test delivery address','+220831000002','INVALID'),'Voucher is invalid or expired') from offer_test_fixture;
select pg_temp.assert_true((select effective_price=1000.99 from public.marketplace_priced_products where id=(select product_id from offer_test_fixture)),'voucher requires code; ordinary price stays full');
create temp table test_voucher_orders as select public.create_marketplace_order_v3(product_id,1,'Kanifing','Offer test area','Test delivery address','+220831000002',null,null,null,null,'save15',850.84) as id from offer_test_fixture;
select pg_temp.assert_true((select price_at_purchase=850.84 and voucher_code='SAVE15' from public.order_items where order_id=(select id from test_voucher_orders)),'case-insensitive voucher applies and saves code');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub',seller_id::text,true) from offer_test_fixture;
delete from public.product_offers where product_id=(select product_id from offer_test_fixture);
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub',buyer_id::text,true) from offer_test_fixture;
select pg_temp.expect_error(format('select public.create_marketplace_order_v3(%L,1,%L,%L,%L,%L,null,null,null,null,%L,850.84)',product_id,'Kanifing','Offer test area','Test delivery address','+220831000002','SAVE15'),'Voucher is invalid or expired') from offer_test_fixture;
select pg_temp.assert_true((select stock_quantity=17 from public.products where id=(select product_id from offer_test_fixture)),'invalid codes and price mismatches leave stock unchanged');
reset role;
select 'PASS: discounts, vouchers, RLS, stock, delivery, price changes, self-purchase, ended offers' as test_result;

rollback;
